version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-pw

    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"